#!/usr/bin/awk -f
#
# Convert annotation summary file to a psl file (on stdout) #
BEGIN {
FS="\t";
OFS="\t"; }
{
delete ids
split($10, ids, "|");
blockSizes= $11 ","; 
qstarts= 0 ",";
tstarts= $16 ",";
print $11, 0, 0, 0, 0, 0, 0, 0, $9, ids[4], $11, $12, $13, $14, $15, $16, $17, 1, blockSizes, qstarts, tstarts
}

